### ISSUE TITLE
Running APBS through the PDB2PQR web portal Problem

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/electrostatics.github.io#20]
On page: http://www.poissonboltzmann.org/examples/running_apbs_through_pdb2pqr_web_portal/ 
" Once you've finished editing, click the POV-Ray "Run" button to render your image.  " needs to be added to the very end of the document to be verbatim to the old website.

**Comment by sobolevnrm** [comment]
Documentation has moved to https://apbs.readthedocs.io/en/latest/index.html and this problem is obselete.
