### ISSUE TITLE
Orphan Pages and Blank .md Files

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/electrostatics.github.io#23]
Orphan pages:

http://www.poissonboltzmann.org/docs/contributing/ is an orphaned page that has no links on the website

There are also blank example files in the repository:

tutorial_a, tutorial_b, workshop_a, workshop_b

**Comment by sobolevnrm** [comment]
Is the information for these pages included elsewhere on the site?

**Comment by mchun0630** [comment]
No; I couldn’t find it.

**Comment by sobolevnrm** [comment]
OK, we should migrate it.

**Comment by sobolevnrm** [comment]
This problem was resolved when the documentation was moved to https://apbs.readthedocs.io/en/latest/.
