### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by ewallace** [Electrostatics/electrostatics.github.io#33]
Please add citation information to your github website. We would like to cite you properly.

[How to cite software blogpost from software sustainability institute.](https://www.software.ac.uk/how-cite-software)

**Comment by sobolevnrm** [comment]
Hello --

The citation information is given on the individual software packages' pages:

- https://pdb2pqr.readthedocs.io/en/latest/supporting.html#citing-our-software
- https://apbs.readthedocs.io/en/latest/supporting.html#citing-our-software

Were you thinking of something different?

Thank you,

Nathan

**Comment by ewallace** [comment]
Hello  Nathan,

Thanks, that is exactly what we were asking for. I think it would be good to add it (or a link to it) to your README.md at https://github.com/Electrostatics/electrostatics.github.io as well, that is the first place I expect to look for a software citation. In this case another co-author used APBS, I was just checking through things as we were submitting.

Thank you,
Edward

**Comment by sobolevnrm** [comment]
This is fixed in https://github.com/Electrostatics/electrostatics.github.io/commit/00586e268d75cd0f373b189512cfb220bed55fab -- thank you for the suggestion.
